### PR TITLE
use % formatter

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by ArthurJ** [comment]
Hey @EdwardBetts, did you look this project by yourself or you created a bot to look for this pattern on github?

**Comment by EdwardBetts** [comment]
No bot, I was searching github.

**Comment by ArthurJ** [comment]
Thanks for that, since then I take care about how to format percentages. 
And I wrote another project that does the same job in Rust some months ago. If you still have some interest in the topic take a look, https://github.com/ArthurJ/rvoto

(I will translate to English and write a readme later)

**Comment by ArthurJ** [comment]
@jhcloos may want to take a look at well.

**Pull request merged**
